name: Prerelease

on:
  push:
    branches:
      - main

jobs:
  prerelease:
    if: ${{ github.repository_owner == 'threepointone' }}
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - run: bun install

      - name: Modify package.json version
        run: bun .github/version-script.js

      - run: bun run build
      # - run: bun run check

      - run: npm publish --tag beta
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        working-directory: packages/partyflare
