name: Pull Request

on: pull_request

jobs:
  check:
    timeout-minutes: 5
    strategy:
      matrix:
        os: [
            ubuntu-latest
            # windows-latest,
            # macos-latest,
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - run: bun install

      - run: bun run build
      # - run: bun run check
